'''
Exercise 36 – Working with constants
Write a second program that takes again two numbers from the user and calculates new
values with the help of the same functions as in exercise 31. This time the input variables
have to multiplied by one of three shown constants (Pi, Euler number or Tau). Let the user
choose which constant should be used. Print out the results
'''

import math

def maths(prompt1, prompt2, prompt3):
    while True:
        try:
            # First number has to be a float
            Inp1 = float(input(prompt1))
            break
            # User is allowed to advance (out of the loop) for providing
            # a value that can be read as a float...
        except ValueError:
            # or not...
            print("Please input the first number.\n")
            continue
            # Check validity of user input, as immediately above
    while True:
        try:
            Inp2 = float(input(prompt2))
            break
        except ValueError:
            print("Please input the second number.\n")
            continue
    # do the mathematical operation
    Ans = math.pow(Inp1, Inp2)
    # Get the user input for which constant to divide the power value by
    # (for nicer answers)

    # Print the result(s) of the mathematical operation(s)
    print(Ans)
    # While loop bottlenecks you into one of 4 choices
    while True:
        try:
            # First number has to be a float
            Inp3 = int(input(prompt3))
        # User is allowed to advance (out of the loop) for providing
        # a value that can be read as an integer...
        except ValueError:
            # or not...
            print("Please type in a whole number.\n")
            continue
            # And that integer must be one of our choices
        if Inp3 > 4 or Inp3 < 1:
            print("Please input one of the available numbers.\n")
            continue
            # User chose pi
        elif Inp3 == 1:
            print("You have chosen π")
            Inp4 = Ans / math.pi
            print(f'Resulting number divided by π:\n{Inp4}')
            break
            # User chose e
        elif Inp3 ==2:
            print("You have chosen e")
            Inp4 = Ans / math.e
            print(f'Resulting number divided by e:\n{Inp4}')
            break
            # User chose tau
        elif Inp3 ==3:
            print("You have chosen τ")
            Inp4 = Ans / (math.pi * 2)
            print(f'Resulting number divided by τ:\n{Inp4}')
            break
        # User quit
        elif Inp3 ==4:
            print("You have chosen to exit.")
            break
        # Tying loose end
        else:
            print("Don't know how you got this message.")
            break



# Call the function, user input prompts shown in terminal
maths("Please type in a number.\n", "Please type in another, this will act as a power of the first.\nWe will then divide it by one of 3 well-known mathematical constants.\n", "Please input the number signifying your choice to divide the number you generated by.\n[1] for pi, [2] for e (Euler's constant) or [3] for tau (2*pi)\n(Select [4] to exit.):\n")
